### ISSUE TITLE
Feature Request: Automatically Log which user started print

### ISSUE THREAD

**Issue by jmiltxtav** [imrahil/OctoPrint-PrintHistory#96] opened 2023-05-31 16:09 UTC
I have an instance where around 15 people have access to the printer. I want to log which user starts the print. 

I see the option to go in afterward and mark which user started the print, but I would like that to be automatic because they will not go back and edit the history. From what I see in the code, we might be able to add a column using the [printing event](https://docs.octoprint.org/en/maintenance/events/index.html#printing) hook. 

I can attempt to add this as well, but I am unsure how everything relates to everything else, so I would prefer if one of the devs could add it.

**Comment by guysoft** [comment] 2023-11-07 14:43
You are welcome to try and add this. I have my hands full at the moment and would not get to this in the future

**Comment by WildRikku** [comment] 2024-09-02 15:04
this is also kind of a duplicate of #20 (even though that issue originally was about being able to log the user at all, now it's about automatically adding the user, which seems not to be possible currently)

**Closed** 2024-09-03 13:53 UTC
